sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: yzh1019
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx1831d320f297a2c8
    secret: 99b037bdbc5f677bc91defa99a87c318